set nocompatible              
filetype on
set rtp+=~/.vim/bundle/Vundle.vim  
 
"" vundle初始化 
call vundle#begin()  
call vundle#end()          
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

"--------------------------------------- 
set backspace=2 
set number
let g:gruvbox_italic=1
set encoding=utf-8
set fileencodings=utf-8,gbk,ucs-bom,gb18030,gb2312,cp93
syntax on
filetype plugin indent on

" Nerdtree ------------------------------
map <F2> :NERDTreeToggle<CR>
" " open nerdtree with the current file selected
nmap ,t :NERDTreeFind<CR>
" " don;t show these file types
let NERDTreeIgnore = ['\.pyc$', '\.pyo$']

" Tagbar ------------------------------
let g:tagbar_width=30
map <F8> :TagbarToggle<CR>

" CtrlP ------------------------------
let g:ctrlp_map = '<c-f>'
" tags (symbols) in current file finder mapping
nmap ,g :CtrlPBufTag<CR>
" tags (symbols) in all files finder mapping
nmap ,G :CtrlPBufTagAll<CR>
" general code finder in all files mapping
nmap ,f :CtrlPLine<CR>
" recent files finder mapping
nmap ,m :CtrlPMRUFiles<CR>
" commands finder mapping
nmap ,c :CtrlPCmdPalette<CR>
" to be able to call CtrlP with default search text
function! CtrlPWithSearchText(search_text, ctrlp_command_end)
    execute ':CtrlP' . a:ctrlp_command_end
    call feedkeys(a:search_text)
endfunction
        " same as previous mappings, but calling with current word asdefault text
nmap ,wg :call CtrlPWithSearchText(expand('<cword>'), 'BufTag')<CR>
nmap ,wG :call CtrlPWithSearchText(expand('<cword>'),'BufTagAll')<CR>
nmap ,wf :call CtrlPWithSearchText(expand('<cword>'), 'Line')<CR>
nmap ,we :call CtrlPWithSearchText(expand('<cword>'), '')<CR>
nmap ,pe :call CtrlPWithSearchText(expand('<cfile>'), '')<CR>
nmap ,wm :call CtrlPWithSearchText(expand('<cword>'),'MRUFiles')<CR>
nmap ,wc :call CtrlPWithSearchText(expand('<cword>'),'CmdPalette')<CR>
" don't change working directory
let g:ctrlp_working_path_mode = 0
" ignore these files and folders on file finder
set wildignore+=*/tmp/*,*.so,*.swp,*.zip  
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.git|\.hg|\.svn|node_modules)$',
  \ 'file': '\.pyc$\|\.pyo$',
  \ }

" Ctrlfs ------------------------------
" 快捷键速记法：search in project
let g:ctrlsf_ackprg = 'ack' 
let g:ctrlsf_default_view_mode = 'compact'
nmap     <C-P> <Plug>CtrlSFPrompt
vmap <C-P>f <Plug>CtrlSFVwordPath 
vmap <C-P>F <Plug>CtrlSFVwordExec 
nmap <C-P>n <Plug>CtrlSFCwordPath 
nmap <C-P>p <Plug>CtrlSFPwordPath 
nnoremap <C-P>o :CtrlSFOpen<CR>
nnoremap <C-P>t :CtrlSFToggle<CR>
inoremap <C-P>t <Esc>:CtrlSFToggle<CR>
